### ISSUE TITLE
Category Selection 

### ISSUE THREAD

**Issue by sid10123** [mhdzumair/tamilblasters_stremio_addon#15]
I use this addon almost daily but find i have to continuously scroll past the languages i don't understand. An option to hide ones i don't use will be greatly appreciated.

**Comment by mhdzumair** [comment]
Do you mean when you select the stream video?

**Comment by sid10123** [comment]
Hi! No i meant when scrolling through the library on Stremio, i see
multiple categories /languages that i have to scroll past to find the
relevant ones. An settings option alongside the install which allows you to
exclude certain languages would be great. Either way, great add on.

**Comment by mhdzumair** [comment]
@sid10123 Thanks for suggesting this. Now you can configure the preferred languages for movies and series. Except for TamilBlasters home page movies. 

Link to Configure → https://882b9915d0fe-stremio-tamilblasters.baby-beamup.club/configure

![image](https://github.com/mhdzumair/tamilblasters_stremio_addon/assets/44891939/0e3fa32b-23f6-4ac3-94ad-07c27ef6c9b0)

Let me know your suggestions.

**Comment by sid10123** [comment]
Many thanks, much appreciated.

**Comment by cg8440** [comment]
Hi. Thanks for providing options to choose the language. However, it would be nice if we could choose category instead of just the language. For example, if I select tamil languaue, than I have all categories like Tamil HD movies, Tamil DVD-scr/HDcam, Tamil dubbed etc. I would like to select just Tamil HD movies and be able to hide all other Tamil categories. Same for other languages. I want to hide dubbed movies category and hdcam category. Is that possible? Thanks for all your time.
